[package]
name = "ultimate_hacking_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gethostname = "0.4.1"
lemmeknow = "0.7.0"
log = "0.4.17"
project_ares = "0.7.0"
reqwest = "0.11.13"
serde_json = "1.0.89"
serenity = "0.11.5"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
