apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
      - name: discord
        image: autumnskerritt/ultimate-hacking-bot:1.1.0
        resources:
          limits:
            cpu: "0.3"
            memory: 400Mi
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: DISCORD_TOKEN
      nodeSelector:
        type: worker