version: '3'

services:
  discord_bot:
    image: autumnskerritt/discord_bot:latest
    environment:
      - DISCORD_TOKEN=XXXX
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
